# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  spotify-dotfiles = {
    pname = "spotify-dotfiles";
    version = "5709eac522f8eddd31aecccd49907b9115c17292";
    src = fetchgit {
      url = "git@ghe.spotify.net:maartens/spotify-dotfiles.git";
      rev = "5709eac522f8eddd31aecccd49907b9115c17292";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lJoXvDPUZM5AAMt3ygcBj7mXW6KUmTfKSNwZsZ6+rXk=";
    };
    date = "2026-07-31";
  };
}
