# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  spotify-homebrew-sptaps = {
    pname = "spotify-homebrew-sptaps";
    version = "f6fabe66c072ec7247441605080a40366e2ec75b";
    src = fetchgit {
      url = "git@ghe.spotify.net:shared/homebrew-spotify.git";
      rev = "f6fabe66c072ec7247441605080a40366e2ec75b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-W19Jd61Ft6Pz/e28pH7bWUaYNTJ82Tz8MLpVCR2SirM=";
    };
    date = "2025-11-13";
  };
}
