# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  spotify-homebrew-sptaps = {
    pname = "spotify-homebrew-sptaps";
    version = "1dd58d341407fb59b4104f2ee17c580a615c9c46";
    src = fetchgit {
      url = "git@ghe.spotify.net:shared/homebrew-spotify.git";
      rev = "1dd58d341407fb59b4104f2ee17c580a615c9c46";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-s8Z5siGy/YFS+jLWcUpoLra9BHpbXUc7Vdu48Uk8ul0=";
    };
    date = "2025-09-18";
  };
}
