"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """
$username\
$hostname\
$directory\
${custom.jj}\
$line_break\
$python\
$character
"""
right_format = """
$cmd_duration
"""

[cmd_duration]
min_time = 1000
show_milliseconds = true
format = "[$duration]($style)"
style = "yellow"

[directory]
style = "blue"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](purple)"

[git_branch]
disabled = true
format = "[$branch]($style)"
style = "bright-black"

[git_status]
disabled = true
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"

[git_state]
disabled = true
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = 'bright-black'

[python]
format = "[$virtualenv]($style)"
style = "bright-black"

[custom.jj]
when = "jj-starship detect"
shell = [
  "jj-starship",
  "--strip-bookmark-prefix",
  "maartens/",
  "--jj-symbol",
  " ",
]
format = "$output "
